modLoader="javafml"
loaderVersion="[47,)"
license="${modLicense}"
issueTrackerURL="${modIssueTrackerUrl}"

[[mods]]
modId="${modId}"
version="${modVersion}"
displayName="${modName}"
authors="${modAuthors}"
description='''
${modDescription}
'''

[[dependencies.${modId}]]
modId="forge"
mandatory=true
versionRange="[${forgeVersion},)"
ordering="NONE"
side="BOTH"

[[dependencies.${modId}]]
modId="minecraft"
mandatory=true
versionRange="[${minecraftVersion},1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.${modId}]]
modId="kotlinforforge"
mandatory=true
versionRange="[${kotlinForForgeVersion},)"
ordering="NONE"
side="BOTH"

[[dependencies.${modId}]]
modId="create"
mandatory=true
versionRange="[${createReleaseVersion},6.1.0)"
ordering="AFTER"
side="BOTH"

[[dependencies.${modId}]]
modId="create_new_age"
mandatory=true
versionRange="[${createNewAgeVersion},)"
ordering="AFTER"
side="BOTH"

[[dependencies.${modId}]]
modId="chemlib"
mandatory=true
versionRange="[${chemlibVersion},)"
ordering="AFTER"
side="BOTH"

[[dependencies.${modId}]]
modId="alchemylib"
mandatory=true
versionRange="[${alchemylibVersion},)"
ordering="AFTER"
side="BOTH"

[[dependencies.${modId}]]
modId="alchemistry"
mandatory=true
versionRange="[${alchemistryVersion},)"
ordering="AFTER"
side="BOTH"

[[dependencies.${modId}]]
modId="emi"
mandatory=false
versionRange="[${emiVersion},)"
ordering="AFTER"
side="CLIENT"

[[dependencies.${modId}]]
modId="jei"
mandatory=false
versionRange="[${jeiVersion},)"
ordering="AFTER"
side="CLIENT"

[[dependencies.${modId}]]
modId="kubejs"
mandatory=false
versionRange="[2001,)"
ordering="AFTER"
side="BOTH"
